/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formViews;

import controller.AquisicaoJpaController;
import controller.ProdutoJpaController;
import controller.VendaJpaController;
import model.Aquisicao;
import model.Loja;
import model.Produto;
import model.Venda;
import java.util.Date;
import javax.swing.JOptionPane;
import mainViews.MainLoja;
import productsView.VendasView;

/**
 *
 * @author aderito
 */
public class RegistarVenda extends javax.swing.JFrame {
    Loja loja;
    Venda venda;
    VendasView vendasView;
    MainLoja mainLoja;
    AquisicaoJpaController ajc;
    VendaJpaController vjc;
    Produto produto;
    Aquisicao aquisicao;
    ProdutoJpaController pjc;
    
    /**
     * Creates new form registarVenda
     */
    public RegistarVenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        title_regVenda = new javax.swing.JLabel();
        cBox_produto = new javax.swing.JComboBox<>();
        btn_registarVenda = new javax.swing.JButton();
        spinner_qtdVenda = new javax.swing.JSpinner();
        datePicker_dataVenda = new org.jdesktop.swingx.JXDatePicker();
        btn_goBack_MainLoja = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel1.setText("Nome do Produto");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel3.setText("Data de Venda");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel2.setText("Quantidade");

        title_regVenda.setFont(new java.awt.Font("Arial Black", 1, 15)); // NOI18N
        title_regVenda.setText("Registar Venda");

        cBox_produto.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        cBox_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBox_produtoActionPerformed(evt);
            }
        });

        btn_registarVenda.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        btn_registarVenda.setText("vender");
        btn_registarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registarVendaActionPerformed(evt);
            }
        });

        spinner_qtdVenda.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N

        datePicker_dataVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datePicker_dataVendaActionPerformed(evt);
            }
        });

        btn_goBack_MainLoja.setText("<--");
        btn_goBack_MainLoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_goBack_MainLojaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(270, Short.MAX_VALUE)
                .addComponent(btn_registarVenda)
                .addGap(274, 274, 274))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cBox_produto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spinner_qtdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(datePicker_dataVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_goBack_MainLoja)
                                .addGap(183, 183, 183)
                                .addComponent(title_regVenda)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title_regVenda)
                    .addComponent(btn_goBack_MainLoja))
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cBox_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datePicker_dataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinner_qtdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(btn_registarVenda)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datePicker_dataVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datePicker_dataVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datePicker_dataVendaActionPerformed

    private void btn_registarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registarVendaActionPerformed
        vendasView = new VendasView();
        venda = new Venda();
        vjc = new VendaJpaController();
        
        int qtdAvender = (Integer) spinner_qtdVenda.getValue();
        Date dataVenda = datePicker_dataVenda.getDate();
        
        if((aquisicao.getQtdAdquirida() > 0) 
                && (aquisicao.getQtdAdquirida() >= qtdAvender)){
            int qtdAdquirida = aquisicao.getQtdAdquirida();
            
            venda.setDataVenda(dataVenda);
            venda.setQtdVendido(qtdAvender);
            venda.setIdproduto(produto);
        
            try {
                
                vjc.create(venda);

                aquisicao.setQtdAdquirida(qtdAdquirida - qtdAvender);
              
                ajc.edit(aquisicao);
                
                JOptionPane.showMessageDialog(null
                        , "Venda registada com sucesso!"
                        , "Mensagem"
                        , JOptionPane.INFORMATION_MESSAGE);

                dispose();
                vendasView.setIdLoja(loja);
                vendasView.setVisible(true);
            
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null
                    , ex.getMessage()
                    , "Mensagem de Erro"
                    , JOptionPane.ERROR_MESSAGE);
            }
            
        } else{
            JOptionPane.showMessageDialog(null
                    , "A quantidade do produto no stock e insuficiente!"
                    , "Mensagem de Erro"
                    , JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btn_registarVendaActionPerformed

    private void btn_goBack_MainLojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_goBack_MainLojaActionPerformed
        // TODO add your handling code here:
        
        dispose();
        mainLoja = new MainLoja();
        mainLoja.setLoja(loja);
        mainLoja.setVisible(true);
    }//GEN-LAST:event_btn_goBack_MainLojaActionPerformed

    private void cBox_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBox_produtoActionPerformed
        // TODO add your handling code here:
        ajc = new AquisicaoJpaController();
        
        produto = (Produto) cBox_produto.getSelectedItem();
        aquisicao = ajc.findAquisicao(produto.getIdproduto());
        
        spinner_qtdVenda.setValue(aquisicao.getQtdAdquirida());
    }//GEN-LAST:event_cBox_produtoActionPerformed

    public void setIdLoja(Loja shop){
        loja = shop;
        aquisicao = new Aquisicao();
        ajc = new AquisicaoJpaController();
        pjc = new ProdutoJpaController();
        
        for(Produto p: pjc.buscarProdutosPorLoja(loja.getIdloja())){
            aquisicao = ajc.findAquisicao(p.getIdproduto());
            
            if(aquisicao.getQtdAdquirida() > 0){
                cBox_produto.addItem(p);
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistarVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new RegistarVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_goBack_MainLoja;
    private javax.swing.JButton btn_registarVenda;
    private javax.swing.JComboBox<Object> cBox_produto;
    private org.jdesktop.swingx.JXDatePicker datePicker_dataVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner spinner_qtdVenda;
    private javax.swing.JLabel title_regVenda;
    // End of variables declaration//GEN-END:variables
}
