/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package productsView;

import controller.AquisicaoJpaController;
import controller.ProdutoJpaController;
import entitys.Aquisicao;
import entitys.Loja;
import entitys.Produto;
import entitys.TableModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import mainViews.MainLoja;

/**
 *
 * @author aderito
 */
public class AquisicoesView extends javax.swing.JFrame {
    Loja loja;
    MainLoja mainLoja;
    /**
     * Creates new form AquisicoesView
     */
    public AquisicoesView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_goBackMainLoja = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProdutos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        jLabel1.setText("Produtos em stock");

        btn_goBackMainLoja.setText("<--");
        btn_goBackMainLoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_goBackMainLojaActionPerformed(evt);
            }
        });

        jTableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableProdutos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_goBackMainLoja)
                        .addGap(176, 176, 176)
                        .addComponent(jLabel1)
                        .addGap(0, 223, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_goBackMainLoja)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_goBackMainLojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_goBackMainLojaActionPerformed
        // TODO add your handling code here:
//        JOptionPane.showMessageDialog(null, loja.toString());
        
        dispose();
        mainLoja = new MainLoja();
        mainLoja.setLoja(loja);
        mainLoja.setVisible(true);
    }//GEN-LAST:event_btn_goBackMainLojaActionPerformed

    public void setIdLoja(Loja shop){
        loja = shop;
        
        fillTable();
    }

    public void fillTable(){
        Aquisicao aquisicao;
        ProdutoJpaController pjc = new ProdutoJpaController();
        AquisicaoJpaController ajc = new AquisicaoJpaController();
        
        ArrayList data = new ArrayList();
        String[] columns = new String[]{"Nome"
                , "Fornecedor"
                , "Quantidade"
                , "Data_aquisicao"
                , "Preco_compra"};
        
        try {
            
            for(Produto p: pjc.buscarProdutosPorLoja(loja.getIdloja())){
                aquisicao = ajc.findAquisicao(p.getIdproduto());
                
                if(aquisicao.getQtdAdquirida() > 0){
                    data.add(new Object[]{p.getNome()
                            , aquisicao.getIdfornecedor().getNome()
                            , aquisicao.getQtdAdquirida()
                            , aquisicao.getDataAquisicao()
                            , p.getPrecoCompra()});
                }
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error filling arraylist! Error message: "+ e);
        }
        
        TableModel model = new TableModel(data, columns);
        jTableProdutos.setModel(model);
        
        for(int i=0; jTableProdutos.getColumnCount() > i;i++){
            jTableProdutos.getColumnModel().getColumn(i).setPreferredWidth(100);
            jTableProdutos.getColumnModel().getColumn(i).setResizable(false);
        }
        
        jTableProdutos.getTableHeader().setReorderingAllowed(false);
        jTableProdutos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AquisicoesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AquisicoesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AquisicoesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AquisicoesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AquisicoesView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_goBackMainLoja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProdutos;
    // End of variables declaration//GEN-END:variables
}
