/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package productsView;

import controller.AquisicaoJpaController;
import controller.ProdutoJpaController;
import model.Aquisicao;
import model.Loja;
import model.Produto;
import model.TableModel;
import formViews.CadastrarProduto;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import mainViews.MainLoja;

/**
 *
 * @author aderito
 */
public class AquisicoesView extends javax.swing.JFrame {
    List<Produto> listaProdutos;
    Loja loja;
    MainLoja mainLoja;
    CadastrarProduto cadastrarProduto;
    Produto produto;
    ProdutoJpaController pjc;
    Aquisicao aquisicao;
    AquisicaoJpaController ajc;
    
    Date fromDate, toDate;
    
    
    /**
     * Creates new form AquisicoesView
     */
    public AquisicoesView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_goBackMainLoja = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProdutos = new javax.swing.JTable();
        txt_searchField = new javax.swing.JTextField();
        btn_searchProd = new javax.swing.JButton();
        btn_cadProd = new javax.swing.JButton();
        btn_deleteProd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        fromDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel3 = new javax.swing.JLabel();
        toDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        jLabel1.setText("Produtos em stock");

        btn_goBackMainLoja.setText("<--");
        btn_goBackMainLoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_goBackMainLojaActionPerformed(evt);
            }
        });

        jTableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableProdutos);

        txt_searchField.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        txt_searchField.setForeground(new java.awt.Color(165, 151, 151));
        txt_searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_searchFieldKeyPressed(evt);
            }
        });

        btn_searchProd.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        btn_searchProd.setText("Procurar");
        btn_searchProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchProdActionPerformed(evt);
            }
        });

        btn_cadProd.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        btn_cadProd.setForeground(new java.awt.Color(21, 159, 21));
        btn_cadProd.setText("Adicionar");
        btn_cadProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadProdActionPerformed(evt);
            }
        });

        btn_deleteProd.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        btn_deleteProd.setForeground(new java.awt.Color(220, 15, 15));
        btn_deleteProd.setText("Eliminar");
        btn_deleteProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteProdActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel2.setText("Por data:");

        fromDatePicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromDatePickerActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel3.setText("a");

        toDatePicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toDatePickerActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jLabel4.setText("Por nome:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_cadProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_deleteProd))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_goBackMainLoja)
                                .addGap(182, 182, 182)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_searchProd))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fromDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(toDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 177, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_goBackMainLoja)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fromDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_searchProd)
                    .addComponent(btn_deleteProd, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cadProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_goBackMainLojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_goBackMainLojaActionPerformed
        // TODO add your handling code here:
//        JOptionPane.showMessageDialog(null, loja.toString());
        
        dispose();
        mainLoja = new MainLoja();
        mainLoja.setLoja(loja);
        mainLoja.setVisible(true);
    }//GEN-LAST:event_btn_goBackMainLojaActionPerformed

    private void btn_deleteProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteProdActionPerformed
        // TODO add your handling code here:
        int nrRow = jTableProdutos.getSelectedRow();
        
        if(nrRow >= 0){
            pjc = new ProdutoJpaController();
            produto = pjc.findProduto((Integer) jTableProdutos.getValueAt(nrRow, 0));

            try {
                pjc.destroy(produto.getIdproduto());
                fillTable(pjc.buscarProdutosPorLoja(loja.getIdloja()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error message: "+ e);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Nenhum item selecionado! Selecione um item para apagar.");
        }
    }//GEN-LAST:event_btn_deleteProdActionPerformed

    private void btn_cadProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadProdActionPerformed
        dispose();
        cadastrarProduto = new CadastrarProduto();
        cadastrarProduto.setIdLoja(loja);
        cadastrarProduto.setVisible(true);
    }//GEN-LAST:event_btn_cadProdActionPerformed

    private void btn_searchProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchProdActionPerformed
        String searchField = txt_searchField.getText();
        pjc = new ProdutoJpaController();
        
        if(!searchField.equals("")){
            fillTable(pjc.buscarProdutosPorNome(searchField));
        }else{
            JOptionPane.showMessageDialog(null, "Campo de pesquisa em branco!");
        }
    }//GEN-LAST:event_btn_searchProdActionPerformed

    private void txt_searchFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchFieldKeyPressed

    private void fromDatePickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromDatePickerActionPerformed
        // TODO add your handling code here:
        fromDate = fromDatePicker.getDate();
    }//GEN-LAST:event_fromDatePickerActionPerformed

    private void toDatePickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toDatePickerActionPerformed
        // TODO add your handling code here:
        toDate = toDatePicker.getDate();
        
        if(fromDate!=null){
            fillTable(pjc.buscarProdutosPorData(fromDate, toDate, listaProdutos));
        }else{
            JOptionPane.showMessageDialog(null, "Campo da data inicial em branco!");
        }
    }//GEN-LAST:event_toDatePickerActionPerformed

    
    public void setIdLoja(Loja shop){
        loja = shop;
        listaProdutos = new ArrayList<>();
        pjc = new ProdutoJpaController();
        listaProdutos = pjc.buscarProdutosPorLoja(loja.getIdloja());
        
        fillTable(listaProdutos);
    }

    public void fillTable(List<Produto> produtos){
        aquisicao = new Aquisicao();
        ajc = new AquisicaoJpaController();
        
        ArrayList data = new ArrayList();
        String[] columns = new String[]{"Cod."
                , "Nome"
                , "Fornecedor"
                , "Quantidade"
                , "Data_aquisicao"
                , "Preco_compra"};
        
        try {
            
            produtos.stream().map((p) -> {
                aquisicao = ajc.findAquisicao(p.getIdproduto());
                return p;
            }).filter((p) -> (aquisicao.getQtdAdquirida() > 0)).forEachOrdered((p) -> {
                data.add(new Object[]{p.getIdproduto()
                        , p.getNome()
                        , aquisicao.getIdfornecedor().getNome()
                        , aquisicao.getQtdAdquirida()
                        , aquisicao.getDataAquisicao()
                        , p.getPrecoCompra()});
            });
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error filling arraylist! Error message: "+ e);
        }
        
        TableModel model = new TableModel(data, columns);
        jTableProdutos.setModel(model);
        
        for(int i=0; jTableProdutos.getColumnCount() > i;i++){
            jTableProdutos.getColumnModel().getColumn(i).setPreferredWidth(100);
            jTableProdutos.getColumnModel().getColumn(i).setResizable(false);
        }
        
        jTableProdutos.getTableHeader().setReorderingAllowed(false);
        jTableProdutos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AquisicoesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AquisicoesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AquisicoesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AquisicoesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AquisicoesView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadProd;
    private javax.swing.JButton btn_deleteProd;
    private javax.swing.JButton btn_goBackMainLoja;
    private javax.swing.JButton btn_searchProd;
    private org.jdesktop.swingx.JXDatePicker fromDatePicker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProdutos;
    private org.jdesktop.swingx.JXDatePicker toDatePicker;
    private javax.swing.JTextField txt_searchField;
    // End of variables declaration//GEN-END:variables
}
