/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package productsView;

import controller.ProdutoJpaController;
import controller.VendaJpaController;
import entitys.Loja;
import entitys.Produto;
import entitys.TableModel;
import entitys.Venda;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import mainViews.MainLoja;

/**
 *
 * @author aderito
 */
public class VendasView extends javax.swing.JFrame {
    Loja loja;
    /**
     * Creates new form VendasView
     */
    public VendasView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_goBackMainLoja = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVendas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        jLabel1.setText("Vendas efectuadas");

        btn_goBackMainLoja.setText("<--");
        btn_goBackMainLoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_goBackMainLojaActionPerformed(evt);
            }
        });

        jTableVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableVendas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_goBackMainLoja)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(226, 226, 226))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_goBackMainLoja)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_goBackMainLojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_goBackMainLojaActionPerformed
        // TODO add your handling code here:
        MainLoja mainLoja;
        
        dispose();
        mainLoja = new MainLoja();
        mainLoja.setLoja(loja);
        mainLoja.setVisible(true);
    }//GEN-LAST:event_btn_goBackMainLojaActionPerformed

    public void setIdLoja(Loja shop){
        loja = shop;
        
        fillTable();
    }
    
    public void fillTable(){
        Produto produto; 
        VendaJpaController vjc = new VendaJpaController();
        ProdutoJpaController pjc = new ProdutoJpaController();
        
        ArrayList data = new ArrayList();
        String[] columns = new String[]{"Nome_Produto"
                , "Data_venda"
                , "Quantidade"
                , "Preco_venda"};
        
        try {
            
            for(Venda v: vjc.findVendaEntities()){  
                produto = pjc.findProduto(v.getIdproduto().getIdproduto());
                        
                if(produto.getIdloja().getIdloja() == loja.getIdloja()){
                    data.add(new Object[]{v.getIdproduto().getNome()
                            , v.getDataVenda()
                            , v.getQtdVendido()
                            , v.getIdproduto().getPrecoVenda()});
                }
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error filling arraylist! Error message: "+ e);
        }
        
        TableModel model = new TableModel(data, columns);
        jTableVendas.setModel(model);
        
        for(int i=0; jTableVendas.getColumnCount() > i;i++){
            jTableVendas.getColumnModel().getColumn(i).setPreferredWidth(100);
            jTableVendas.getColumnModel().getColumn(i).setResizable(false);
        }
        
        jTableVendas.getTableHeader().setReorderingAllowed(false);
        jTableVendas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendasView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_goBackMainLoja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVendas;
    // End of variables declaration//GEN-END:variables
}
